/pudu/controller_manager:
  ros__parameters:
    update_rate: 100
  
    omni_wheel_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


/pudu/joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
    frame_id: base_footprint


/pudu/omni_wheel_drive_controller:
  ros__parameters:
    wheel_offset: 0.785398
    wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint", "rear_right_wheel_joint", "front_right_wheel_joint"]
    robot_radius: 0.311
    wheel_radius: 0.1
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    open_loop: false
    position_feedback: true
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    tf_frame_prefix: "/"